services:
  tensorflow:
    container_name: tensorflow
    volumes:
      - ~/dataset:/tf/dataset
      - ~/tf:/tf/triplet-fingerprinting
    # ports:
      # - 28888:8888
    image: tensorflow/tensorflow:latest-gpu
    # dummy command to keep running
    command: tail -f /dev/null
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu

                
